using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StockSimulationMVC.Models
{
    public class BasicFinancialDataModel
    {
        public double ID { get; set; }
        public int Company { get; set; }
        public string CompanyName { get; set; }
        public DateTime Date { get; set; }
        public double? Quarter { get; set; }
        public double? consolidation_Y_N_ { get; set; }
        public double? Qly_Q__Half_H_ { get; set; }
        public double? Currency { get; set; }
        public double? Cash_CashEquivalent_Consol { get; set; }
        public double? MarketableSecurity_Consol { get; set; }
        public double? A_R_N_R_Consol { get; set; }
        public double? LoanToOther_S_T { get; set; }
        public double? OtherReceivable_Consol { get; set; }
        public double? Inventories_Consol { get; set; }
        public double? Prepaid_Advance_Consol { get; set; }
        public double? OtherCurrentAssets_Consol { get; set; }
        public double? TotalCurrentAssets_Consol { get; set; }
        public double? Long_termInvestment_Consol { get; set; }
        public double? TotalFixedAssets_Consol { get; set; }
        public double? TotalOtherAssets_Consol { get; set; }
        public double? TotalAssets_Consol { get; set; }
        public double? TotalCurrentLiab__Consol { get; set; }
        public double? L_TLiabilities_Consol { get; set; }
        public double? TotalOtherL_TLiab_Consol { get; set; }
        public double? TotalLiabilities_Consol { get; set; }
        public double? CommonStocks_Consol { get; set; }
        public double? PreferredStocks_Consol { get; set; }
        public double? Proceeds_NewIssued_Consol { get; set; }
        public double? Res__CapitalIncrease_Consol { get; set; }
        public double? CapitalReserve_Consol { get; set; }
        public double? LegalReserve_Consol { get; set; }
        public double? AppropriatedR_E_Consol { get; set; }
        public double? UnappropriatedR_E_Consol { get; set; }
        public double? Valu_Loss_L_TInv__Consol { get; set; }
        public double? AdjustmentForFX_Consol { get; set; }
        public double? TotalEquity_Consol { get; set; }
        public double? TotalLiab__Equity_Consol { get; set; }
        public double? NetSales_Consol { get; set; }
        public double? CostOfGoodsSold_Consol { get; set; }
        public double? GrossProfit_Consol { get; set; }
        public double? Unearned_RelatedSale_Consol { get; set; }
        public double? OperatingExpenses_Consol { get; set; }
        public double? OperatingIncome_Consol { get; set; }
        public double? InterestIncome { get; set; }
        public double? InvestmentIncome { get; set; }
        public double? Gain_DisposalInv_ { get; set; }
        public double? Rev_LossonInv_ { get; set; }
        public double? Gain_DisposalF_A { get; set; }
        public double? Rev_LossonInvty { get; set; }
        public double? Rev_LossonImpair { get; set; }
        public double? ExchangeGain { get; set; }
        public double? OtrNon_OperateInc_ { get; set; }
        public double? TotalNon_Op_Income { get; set; }
        public double? InterestExpenses { get; set; }
        public double? InvestmentLoss { get; set; }
        public double? Loss_DisposalInv_ { get; set; }
        public double? Loss_InvRevaluat { get; set; }
        public double? Loss_DisposalF_A { get; set; }
        public double? LossonImpaiement { get; set; }
        public double? ExchangeLoss { get; set; }
        public double? Valu_LossonInv_ { get; set; }
        public double? OtherNon_Oper_Exp_ { get; set; }
        public double? TotalNon_Op_Exp_ { get; set; }
        public double? Pre_TaxIncome { get; set; }
        public double? IncomeTaxExpense_Consol { get; set; }
        public double? Cont_OPIncome { get; set; }
        public double? Discont_dDpt_G_L_Consol { get; set; }
        public double? ExtraordinaryG_L_Consol { get; set; }
        public double? CumulativeEffects_Consol { get; set; }
        public double? NetIncome_Consol { get; set; }
        public double? EarningPerShare_Consol { get; set; }
        public double? Wght_Avg_Stocks_Consol { get; set; }
        public double? BIT_Consol { get; set; }
        public double? BITDA_Consol { get; set; }
        public double? CashDiv_PerShare_Consol { get; set; }
        public double? StockDiv_ErnP_S_Consol { get; set; }
        public double? StockDiv_CplP_S_Consol { get; set; }
        public double? CashDiv__CommonShr { get; set; }
        public double? CashDivi__Preferred { get; set; }
        public double? StockDiv_CplReserv { get; set; }
        public double? NetIncomeCurrent { get; set; }
        public double? CashFlow_Operating_Consol { get; set; }
        public double? CashFlow_Investment_Consol { get; set; }
        public double? CashFlow_Financing_Consol { get; set; }
        public double? ExchangeInfluence { get; set; }
        public double? ChangeinCashFlow { get; set; }
        public double? Depreciation { get; set; }
        public double? Amortization { get; set; }
        public double? _Purchase_ofFA { get; set; }
        public double? DividendPaid { get; set; }
        public double? NetDEBT { get; set; }
        public double? Tax10Estimate { get; set; }
        public double? Tax10_Consol { get; set; }
        public double? Loans_Discounted_Consol { get; set; }
        public double? Deposits_Consol { get; set; }
        public double? InvestListedStock_Curr_ { get; set; }
        public double? InvestListedStock_NonCurr_ { get; set; }
        public double? ROA_C__EBIDA0_Consol { get; set; }
        public double? ROA_A__EBI0_Consol { get; set; }
        public double? ROA_B__EBITDA0_Consol { get; set; }
        public double? ROE_A__NI_Consol { get; set; }
        public double? ROE_B__NIExDisposal_Consol { get; set; }
        public double? GrossMargin0_Consol { get; set; }
        public double? Real_GrossProfit0_Consol { get; set; }
        public double? OperatingIncome0_Consol { get; set; }
        public double? Pre_TaxIncome0_Consol { get; set; }
        public double? NetIncome0_Consol { get; set; }
        public double? MarkupRatioofPrice_cost { get; set; }
        public double? NetNon_op_Inc__Rev__Consol { get; set; }
        public double? NetIncome0_ExcDisp_Consol { get; set; }
        public double? NumbersofEmployee_Consol { get; set; }
        public double? OperatingExp_0_Consol { get; set; }
        public double? EmployeeFee0_Consol { get; set; }
        public double? R_D0_Consol { get; set; }
        public double? BadDebt_Revenue_Consol { get; set; }
        public double? CFO_CL0_Consol { get; set; }
        public double? Int_Exp__Debt_Consol { get; set; }
        public double? TaxRate_A__Consol { get; set; }
        public double? TaxRate_B__Consol { get; set; }
        public double? BPS_B__Consol { get; set; }
        public double? BPS_A__Consol { get; set; }
        public double? BPS_C__Consol { get; set; }
        public double? Rolling_12MEPS_Consol { get; set; }
        public double? PS_Cashflow_Consol { get; set; }
        public double? PS_Sales_Consol { get; set; }
        public double? PS_OperatingIncome_Consol { get; set; }
        public double? PS_Pre_TaxIncome_Consol { get; set; }
        public double? YOY0_Sales_Consol { get; set; }
        public double? YOY0_GrossMargin_Consol { get; set; }
        public double? YOY0_Real_GM_Consol { get; set; }
        public double? YOY0_Oper_Income_Consol { get; set; }
        public double? YOY0_Pre_TaxIncome_Consol { get; set; }
        public double? YOY0_NetIncome_Consol { get; set; }
        public double? YOY0_Ordin_Income_Consol { get; set; }
        public double? YOY0_NIExDisposal_Consol { get; set; }
        public double? YOY0_TotalAssets_Consol { get; set; }
        public double? YOY0_TotalEquity_Consol { get; set; }
        public double? YOY0_FixedAssets_Consol { get; set; }
        public double? YOY0_ReturnonTA_Consol { get; set; }
        public double? RetentionRatio_Consol { get; set; }
        public double? QOQ0_Sales_Consol { get; set; }
        public double? QOQ0_OperatingInc__Consol { get; set; }
        public double? QOQ0_NetIncome_Consol { get; set; }
        public double? C_FAdequacyRatio_Consol { get; set; }
        public double? CashReinvest0_Consol { get; set; }
        public double? Current0_Consol { get; set; }
        public double? AcidTest_Consol { get; set; }
        public double? InterestExp_0_Consol { get; set; }
        public double? LIAB_ERatio_Consol { get; set; }
        public double? Liabilities0_Consol { get; set; }
        public double? Equity_TA0_Consol { get; set; }
        public double? _L_TLiab_SE__FA0_Consol { get; set; }
        public double? Debt_Eqity0_Consol { get; set; }
        public double? ContingentLiab_Equi_Consol { get; set; }
        public double? TimesInterestEarn_Consol { get; set; }
        public double? Oper_Income_Capital_Consol { get; set; }
        public double? PreTaxIncom_Capital_Consol { get; set; }
        public double? TCRI_Consol { get; set; }
        public double? Inv__A_R_Equity_Consol { get; set; }
        public double? TotalAssetTurnover_Consol { get; set; }
        public double? A_R_N_RTurnover_Consol { get; set; }
        public double? Days_A_RTurnover_Consol { get; set; }
        public double? InventoryTurnover_Consol { get; set; }
        public double? Days_InventoryTurn__Consol { get; set; }
        public double? FixedAssetTurnover_Consol { get; set; }
        public double? EquityTurnover_Consol { get; set; }
        public double? Days_A_PTurnover_Consol { get; set; }
        public double? NetOperatingCycle_Consol { get; set; }
        public double? A_R_NetSale { get; set; }
        public double? Inventory_NetSale { get; set; }
        public double? FreeCashFlow { get; set; }
        public double? DegreeofOp_Lever__Consol { get; set; }
        public double? DegreeofFin_Lever_Consol { get; set; }
        public double? SalesPerEmployee_Consol { get; set; }
        public double? OperationInc__Emply_Consol { get; set; }
        public double? FixedAssets_Emply_Consol { get; set; }
        public double? P_E_Consol { get; set; }
        public double? P_B_Consol { get; set; }
        public double? PSR_Consol { get; set; }
        public double? DividendYield_Consol { get; set; }
        public double? CashDividendYield_Consol { get; set; }
        public double? BerryRatio_Consol { get; set; }
        public double? ReturnOnOP_Assets_Consol { get; set; }
        public double? MarketCap_ { get; set; }


    }
}